### ISSUE TITLE
[BUG] Cargo install fails with no method named parse

### ISSUE THREAD

**Issue by hsanson** [christo-auer/eilmeldung#255]
**Describe the bug**

Installing with cargo fails with recent versions of eilmeldung. This used to work fine with version 1.4.4.

**Screenshot (if applicable)**

**To Reproduce**

```sh
sudo apt install -y rustup build-essential perl libssl-dev pkg-config libxml2-dev clang libsqlite3-dev
cargo install eilmeldung

   Compiling diesel_migrations v2.3.2
error[E0599]: no method named `parse` found for type `i64` in the current scope
   --> /home/ryujin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/news-flash-3.0.2/src/feed_api_implementations/feedbin/mod.rs:245:87
    |
245 |                         filesize: enclosure.enclosure_length.and_then(|length| length.parse::<i32>().ok()),
    |                                                                                       ^^^^^ method not found in `i64`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `news-flash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `eilmeldung v1.5.2`, intermediate artifacts can be found at `/tmp/cargo-installzV4OL4`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_BUILD_BUILD_DIR` to that path.

```

**Expected behavior**

Should install

**Relevant Content of Log File**

**Context**
 - Version:  Cannot install to begin with...
 - OS: Linux
 - Package: cargo install
 - Terminal Emulator: ghostty
 - RSS Provider: Not relevant
 -  Ubuntu 24.04

**Additional context**

**Comment by christo-auer** [comment]
Thanks for opening the issue! Could you try `cargo install eilmeldung --locked` (have a look at #245)

This should be fixed with the next release of news-flash. Until then, you have to compile with locked dependencies. I've already updated the docs.

**Comment by hsanson** [comment]
With `--locked` I can install without problems. Maybe good idea to update the README.

Closing as duplicate of https://github.com/christo-auer/eilmeldung/issues/245

**Comment by christo-auer** [comment]
Thanks! I forgot to add it to `README.md` and just added it to `installation.md`. Thanks for pointing that out!
